package com.czertainly.openapi.codegen;

import java.lang.reflect.Method;
import java.lang.reflect.Parameter;
import java.lang.reflect.Type;
import java.util.List;

/**
 * Generates Java source code for dummy controller implementations.
 * Creates method implementations that return null or default values for primitive types.
 * Also annotates controllers with @SecuritySchemeCategory metadata.
 */
public class CodeGenerator {

    private final TypeResolver typeResolver;
    private final String packageName;
    private final String implClassName;
    private final String baseSecurityClass;
    private final List<String> securitySchemes;

    public CodeGenerator(TypeResolver typeResolver, String packageName, String implClassName,
                         String baseSecurityClass, List<String> securitySchemes) {
        this.typeResolver = typeResolver;
        this.packageName = packageName;
        this.implClassName = implClassName;
        this.baseSecurityClass = baseSecurityClass;
        this.securitySchemes = securitySchemes;
    }

    /**
     * Generates the complete Java source code for a dummy controller implementation.
     */
    public String generateImplementation(Class<?> interfaceClass) {
        StringBuilder code = new StringBuilder();

        String className = interfaceClass.getSimpleName();

        appendPackageDeclaration(code);
        appendImports(code, interfaceClass);
        appendClassDeclaration(code, className, implClassName);
        appendMethodImplementations(code, interfaceClass);
        appendClassClosing(code);

        return code.toString();
    }

    private void appendPackageDeclaration(StringBuilder code) {
        code.append("package ").append(packageName).append(";\n\n");
    }

    private void appendImports(StringBuilder code, Class<?> interfaceClass) {
        // Import the interface
        code.append("import ").append(interfaceClass.getName()).append(";\n");

        // Import Spring annotation
        code.append("import org.springframework.web.bind.annotation.RestController;\n");

        // Import security metadata annotation
        code.append("import com.czertainly.openapi.codegen.SecuritySchemeCategory;\n");

        // Add all non-conflicting imports
        for (String imp : typeResolver.getNonConflictingImports()) {
            code.append("import ").append(imp).append(";\n");
        }

        code.append("\n");
    }

    private void appendClassDeclaration(StringBuilder code, String className, String implClassName) {
        code.append("/**\n");
        code.append(" * Auto-generated dummy implementation of ").append(className).append("\n");
        code.append(" * Generated by DummyControllerGenerator using reflection\n");
        code.append(" * All methods return null or appropriate defaults - for OpenAPI generation only\n");
        code.append(" */\n");
        appendSecuritySchemeCategoryAnnotation(code);
        code.append("@RestController\n");
        code.append("@SuppressWarnings({\"unchecked\", \"rawtypes\"})\n");
        code.append("public class ").append(implClassName);
        code.append(" implements ").append(className).append(" {\n\n");
    }

    /**
     * Generates the @SecuritySchemeCategory annotation with base class and security schemes.
     */
    private void appendSecuritySchemeCategoryAnnotation(StringBuilder code) {
        code.append("@SecuritySchemeCategory(\n");
        code.append("    baseClass = \"").append(baseSecurityClass).append("\",\n");
        code.append("    securitySchemes = {");

        if (securitySchemes != null && !securitySchemes.isEmpty()) {
            for (int i = 0; i < securitySchemes.size(); i++) {
                if (i > 0) {
                    code.append(", ");
                }
                code.append("\"").append(securitySchemes.get(i)).append("\"");
            }
        }

        code.append("}\n");
        code.append(")\n");
    }

    private void appendMethodImplementations(StringBuilder code, Class<?> interfaceClass) {
        for (Method method : interfaceClass.getMethods()) {
            if (method.getDeclaringClass().equals(Object.class)) {
                continue;
            }
            appendMethodImplementation(code, method);
        }
    }

    private void appendMethodImplementation(StringBuilder code, Method method) {
        code.append("    @Override\n");
        code.append("    public ");

        // Return type
        code.append(typeResolver.getTypeName(method.getGenericReturnType()));
        code.append(" ");

        // Method name and parameters
        code.append(method.getName());
        code.append("(");
        appendParameters(code, method.getParameters());
        code.append(")");

        // Exceptions
        appendExceptions(code, method.getGenericExceptionTypes());

        // Method body
        code.append(" {\n");
        appendMethodBody(code, method.getReturnType());
        code.append("    }\n\n");
    }

    private void appendParameters(StringBuilder code, Parameter[] parameters) {
        for (int i = 0; i < parameters.length; i++) {
            if (i > 0) {
                code.append(", ");
            }
            code.append(typeResolver.getTypeName(parameters[i].getParameterizedType()));
            code.append(" ");
            code.append(parameters[i].getName());
        }
    }

    private void appendExceptions(StringBuilder code, Type[] exceptions) {
        if (exceptions.length > 0) {
            code.append(" throws ");
            for (int i = 0; i < exceptions.length; i++) {
                if (i > 0) {
                    code.append(", ");
                }
                code.append(typeResolver.getTypeName(exceptions[i]));
            }
        }
    }

    private void appendMethodBody(StringBuilder code, Class<?> returnType) {
        if (!returnType.equals(void.class)) {
            code.append("        return ");
            code.append(getDefaultValue(returnType));
            code.append(";\n");
        }
    }

    private void appendClassClosing(StringBuilder code) {
        code.append("}\n");
    }

    /**
     * Returns the default value for a given return type.
     * Primitives get their default values, objects get null.
     */
    private String getDefaultValue(Class<?> returnType) {
        if (returnType.equals(boolean.class)) {
            return "false";
        } else if (returnType.equals(byte.class) ||
                returnType.equals(short.class) ||
                returnType.equals(int.class)) {
            return "0";
        } else if (returnType.equals(long.class)) {
            return "0L";
        } else if (returnType.equals(float.class)) {
            return "0.0f";
        } else if (returnType.equals(double.class)) {
            return "0.0";
        } else if (returnType.equals(char.class)) {
            return "'\\u0000'";
        } else {
            return "null";
        }
    }
}