api.version=@apiVersion@
spring.application.name=openapi-generator

# Disable unnecessary Spring Boot features
spring.jmx.enabled=false
spring.datasource.enabled=false
spring.jpa.enabled=false

# SpringDoc configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=false
